---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: "dm848/gateway:v2.2.0"
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gateway"
  namespace: "default"
  labels:
    app: "gateway"
spec:
  ports:
    - port: 80
      nodePort: 13000
  selector:
    app: "gateway"
